#pragma once

#include <map>
#include "lexer.h"
#include "../utils/literalexpressionsyntax.h"
#include "../utils/unaryexpressionsyntax.h"
#include "../utils/binaryexpressionsyntax.h"
#include "../utils/parenthesizedexpressionsyntax.h"
#include "../utils/assignmentexpressionsyntax.h"
#include "../utils/nameexpressionsyntax.h"
#include "../utils/ifexpressionsyntax.h"
#include "../utils/forexpressionsyntax.h"
#include "../utils/whileexpressionsyntax.h"
#include "../utils/syntaxtree.h"

/**
 * @file parser.h
 * @brief Contains the declaration of the Parser class.
 */

 /**
  * @class Parser
  * @brief Represents a parser for the XOR language.
  *
  * The Parser class is responsible for parsing input lines and generating a syntax tree.
  * It provides methods for parsing expressions, matching tokens, and retrieving errors.
  */
class Parser {
public:
    /**
     * @brief Constructs a Parser object with the given input line.
     * @param line The input line to be parsed.
     * @param variables A pointer to the map of variables used in the input line.
     */
    Parser(string line, map<string, void *> *variables);

    /**
     * @brief Parses the input line and generates a syntax tree.
     * @return A pointer to the generated syntax tree.
     */
    SyntaxTree *parse();

    /**
     * @brief Parses a statement.
     * @return A pointer to the parsed statement syntax node.
     */
    ExpressionSyntax *parseStatementExpression();

    /**
     * @brief Parses an expression.
     * @return A pointer to the parsed expression syntax node.
     */
    ExpressionSyntax *parseAssignmentExpression();

    /**
     * @brief Parses a binary expression.
     * @param precedence The precedence of the binary operator.
     * @return A pointer to the parsed binary expression syntax node.
     */
    ExpressionSyntax *parseExpression(int parentPrecedence = 0);

    /**
     * @brief Gets the errors generated during parsing.
     * @return A list of error messages.
     */
    ErrorList getErrors();

private:
    int mPosition = 0; // The current position in the token list.
    vector<SyntaxToken> mTokens; // The list of tokens generated by the lexer.
    ErrorList mErrors; // The list of error messages generated during parsing.
    map<string, void *> *mVariables; // A pointer to the map of variables used in the input line.

    /**
     * @brief Peeks at the token at the specified offset from the current position.
     * @param offset The offset from the current position.
     * @return A pointer to the token at the specified offset, or nullptr if the offset is out of range.
     */
    SyntaxToken *peek(int offset);

    /**
     * @brief Gets the current token.
     * @return A pointer to the current token.
     */
    SyntaxToken *current();

    /**
     * @brief Advances to the next token and returns it.
     * @return A pointer to the next token.
     */
    SyntaxToken *nextToken();

    /**
     * @brief Matches the current token with the specified kind and advances to the next token.
     * @param kind The kind of token to match.
     * @return A pointer to the matched token, or nullptr if the current token does not match the specified kind.
     */
    SyntaxToken *match(SyntaxKind kind);

    /**
     * @brief Parses a primary expression.
     * @return A pointer to the parsed primary expression syntax node.
     */
    ExpressionSyntax *parsePrimaryExpression();

    /**
     * @brief Gets the precedence of the specified binary operator.
     * @param kind The kind of the binary operator.
     * @return The precedence of the binary operator.
     */
    int getBinaryOperatorPrecedence(SyntaxKind kind);

    /**
     * @brief Gets the precedence of the specified unary operator.
     * @param kind The kind of the unary operator.
     * @return The precedence of the unary operator.
     */
    int getUnaryOperatorPrecedence(SyntaxKind kind);
};
